
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Apoorva
 */
public class Area5 extends javax.swing.JFrame {

    /**
     * Creates new form Area5
     */
    public Area5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movies Showing");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sapphire.jpg")));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nariman Point");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 90, 160, 36);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bollywood");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 200, 70, 16);

        jRadioButton3.setBackground(new java.awt.Color(255, 51, 255));
        jRadioButton3.setText("Pyar Ka Punchnama 2");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(340, 290, 153, 25);

        jRadioButton4.setBackground(new java.awt.Color(255, 153, 153));
        jRadioButton4.setText("Shaandar");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(340, 330, 83, 25);

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 0));
        jRadioButton5.setText("Singh Is Bling");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(340, 250, 105, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hollywood");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 370, 58, 16);

        jRadioButton6.setBackground(new java.awt.Color(51, 153, 255));
        jRadioButton6.setText("Spectre");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(350, 480, 73, 25);

        jRadioButton7.setBackground(new java.awt.Color(0, 153, 0));
        jRadioButton7.setText("Goosebumps");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(350, 450, 101, 25);

        jRadioButton8.setBackground(new java.awt.Color(204, 0, 0));
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Hunger Games Mocking Jay Part 1");
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(350, 410, 240, 30);

        jButton2.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 630, 100, 30);

        jButton1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 630, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sugimoto-trylon-theatre-new-york-1976.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Startup sign = new Startup();
                sign.setVisible(true);
                sign.setSize(1000,667);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if( jRadioButton8.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MockingJay sign = new MockingJay();
                sign.setVisible(true);
                sign.setSize(736,736);
            }
        });
         }
         else if( jRadioButton7.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Goosebumps sign = new Goosebumps();
                sign.setVisible(true);
                sign.setSize(612,792);
            }
        });
       }
         else if( jRadioButton6.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Spectre sign = new Spectre();
                sign.setVisible(true);
                sign.setSize(760,760);
            }
        });
       }
         else if( jRadioButton5.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SinghIsBling sign = new SinghIsBling();
                sign.setVisible(true);
                sign.setSize(645,760);
            }
        });
       }
          else if( jRadioButton3.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PKP2 sign = new PKP2();
                sign.setVisible(true);
                sign.setSize(525,759);
            }
        });
       }
          else if( jRadioButton4.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Shaandar sign = new Shaandar();
                sign.setVisible(true);
                sign.setSize(600,792);
            }
        });
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Area5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Area5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Area5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Area5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Area5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    // End of variables declaration//GEN-END:variables
}
