
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Apoorva
 */
public class SeatBooking extends javax.swing.JFrame {

    /**
     * Creates new form SeatBooking
     */
    int Seats;
    public SeatBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seat Booking");
        setBackground(new java.awt.Color(0, 102, 0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sapphire.jpg")));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jLabel4.setText("Seat Booking");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 30, 240, 80);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel1.setText("Number of Seats");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 304, 160, 25);

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLabel2.setText("Class");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(161, 141, 54, 25);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jRadioButton1.setText("Silver (Rs. 200)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(270, 140, 150, 33);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jRadioButton2.setText("Gold (Rs. 300)");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(270, 191, 150, 33);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jRadioButton3.setText("Platinum (Rs. 500)");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(270, 242, 180, 33);

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 400, 140, 39);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(220, 480, 160, 39);

        TF.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        TF.setText("00");
        jPanel1.add(TF);
        TF.setBounds(280, 300, 70, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Startup sign = new Startup();
                sign.setVisible(true);
                sign.setSize(1000,667);
            }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if( jRadioButton1.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SeatBooking2 sign = new SeatBooking2();
                sign.TF_1.setText("Rs. "+Integer.toString(200*Integer.parseInt(SeatBooking.TF.getText())));
                sign.setVisible(true);
                sign.setSize(600,600);
            }
        });
          }
          else if( jRadioButton2.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SeatBooking2 sign = new SeatBooking2();
                sign.TF_1.setText("Rs. "+Integer.toString(300*Integer.parseInt(SeatBooking.TF.getText())));
                sign.setVisible(true);
                sign.setSize(600,600);
            }
        });
          }
          else if( jRadioButton3.isSelected()) {
           setVisible(false);
           dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SeatBooking2 sign = new SeatBooking2();
                sign.TF_1.setText("Rs. "+Integer.toString(500*Integer.parseInt(SeatBooking.TF.getText())));
                sign.setVisible(true);
                sign.setSize(600,600);
            }
        });
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
